#!/usr/bin/env ruby

#scriptdir = File.expand_path(File.dirname(__FILE__))
#catsplit = scriptdir + '/catsplit'

#if !File.exist?(catsplit)
#  puts 'cannot find catsplit executable'
#  exit
#end

if ARGV.length < 2
  puts 'need 2 arguments: drive to dump, image file to dump to'
  exit
end

infile = ARGV[0]
outfile = ARGV[1]

if !File.exist?(infile)
  puts 'drive does not exist'
  exit
end

if File.exist?(outfile)
  puts 'out file already exists'
  exit
end

infile = File.expand_path(infile)
outfile = File.expand_path(outfile)

if Process.uid != 0
  puts 'needs to be run as root'
  exit
end

if outfile[/\.img\.gz$/]
  system("dd if=#{infile} bs=256k | gzip > #{outfile}")
  exit
end

if outfile[/\.img$/]
  system("dd if=#{infile} bs=256k of=#{outfile}")
  exit
end

puts 'unsupported image format'
